language: node_js

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq yasm

before_script:
  - "echo 1 | ./chinachu installer"

notifications:
  email: false

branches:
  except:
    - devel-usushio
